# Loads default set of integrations. Do not remove.        
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

rest_command:
  trigger_garage:
    url: "http://100.72.98.73:5000/trigger?token=myGarage_92kL_secure"
    method: GET

input_boolean:
  actron_manual_override:
    name: Actron Manual Override
    icon: mdi:hand-back-right